module.exports = ()=>{
  const testingUser = [{
    "name": "주홍철",
    "age": 25,
    "disease": "천식"
  }, {
    "name": "문선균",
    "age": 25,
    "disease": "정상"
  }, {
    "name": "박병윤",
    "age": 22,
    "disease": "정상"
  }, {
    "name": "송선빈",
    "age": 22,
    "disease": "정상"
  }, {
    "name": "유명환",
    "age": 40,
    "disease": "흡연"
  }, {
    "name": "원빈",
    "age": 30,
    "disease": "정상"
  }, {
    "name": "류성룡",
    "age": 31,
    "disease": "정상"
  }, {
    "name": "이순신",
    "age": 60,
    "disease": "정상"
  }, {
    "name": "최범석",
    "age": 22,
    "disease": "정상"
  }, {
    "name": "정지원",
    "age": 22,
    "disease": "정상"
  }, {
    "name": "미스터김",
    "age": 50,
    "disease": "정상"
  }, {
    "name": "양영주",
    "age": 25,
    "disease": "정상"
  }];
    return testingUser;
}